name: Deploy Javadoc

on:
  push:
    branches:
      - 'master'

jobs:
  deploy-javadoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
          java-package: 'jdk+fx'

      - name: Build docs
        run: chmod +x ./gradlew && ./gradlew javadoc

      - name: Deploy docs to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/docs/javadoc
          CLEAN: true # Automatically remove deleted files from the deploy branch